version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - 3030:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
  alertmanager:
    image: prom/alertmanager:v0.25.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/config/alertmanager
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager/alertmanager.yaml


volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
